version: '3.8'

networks:
  default:
    name: ${MINECRAFT_NETWORK:-games}

# https://hub.docker.com/r/itzg/minecraft-server

services:
  minecraft:
    image: itzg/minecraft-server:${MINECRAFT_DOCKER_TAG:-latest}
    container_name: ${MINECRAFT_CONTAINER_NAME:-minecraft-paper}
    hostname: ${MINECRAFT_HOSTNAME:-minecraft}
    restart: ${MINECRAFT_RESTART:-unless-stopped}
    environment:
      - EULA=true
      - ENABLE_RCON=${MINECRAFT_ENABLE_RCON:-true}
      - TYPE=${MINECRAFT_TYPE:-PAPER}
      - VIEW_DISTANCE=${MINECRAFT_VIEW_DISTANCE:-10}
      - MEMORY=${MINECRAFT_MEMORY:-2G}
      - CONSOLE=${MINECRAFT_CONSOLE:-false}
      - VANILLATWEAKS_SHARECODE=${MINECRAFT_VANILLATWEAKS_SHARECODE:-jjOJob,o85sA9,lJvdCt}
    ports:
      - ${MINECRAFT_PORT:-25565}:25565
      # uncomment if you have geyser installed, https://geysermc.org/
      #- ${MINCRAFT_GEYSER_PORT:-19132}:19132/udp
    volumes:
      - ./etc/games/${MINECRAFT_HOSTNAME:-minecraft}:/data
    labels:
      - joyride.host.name=${MINECRAFT_HOSTNAME:-minecraft}.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
