version: '3.8'

networks:
  default:
    name: ${MICECRAFT_SKYFACTORY_NETWORK:-games}

# https://hub.docker.com/r/itzg/minecraft-server

services:
  minecraft-skyfactory4:
    image: itzg/minecraft-server:${MINECRAFT_SKYFACTORY_DOCKER_TAG:-latest}
    container_name: ${MINECRAFT_SKYFACTORY_CONTAINER_NAME:-minecraft_skyfactory4}
    hostname: ${MINECRAFT_SKYFACTORY_HOSTNAME:-minecraft_skyfactory4}
    restart: ${MICECRAFT_SKYFACTORY_RESTART:-unless-stopped}
    environment:
      - EULA=true
      - ENABLE_RCON=${MICECRAFT_SKYFACTORY_ENABLE_RCON:-true}
      - CF_SERVER_MOD=SkyFactory-4_Server_4_2_4.zip
      - TYPE=${MICECRAFT_SKYFACTORY_TYPE:-CURSEFORGE}
      - VIEW_DISTANCE=${MICECRAFT_SKYFACTORY_VIEW_DISTANCE:-10}
      - MEMORY=${MICECRAFT_SKYFACTORY_MEMORY:-4G}
      - INIT_MEMORY=8G
      - MAX_MEMORY=12G
      - USE_AIKAR_FLAGS=true
      - USE_LARGE_PAGES=true
      - CONSOLE=${MICECRAFT_SKYFACTORY_CONSOLE:-false}
    ports:
      - ${MICECRAFT_SKYFACTORY_PORT:-25565}:25565
      # uncomment if you have flood gate installed
      #- ${MINECRAFT_FLOODGATE_PORT:-19132}:19132/udp
    volumes:
      - ./etc/games/${MICECRAFT_SKYFACTORY_HOSTNAME:-minecraft_skyfactory4}:/data
    labels:
      - joyride.host.name=${MINECRAFT_HOSTNAME:-minecraft_skyfactory4}.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
