version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/itzg/minecraft-bedrock-server

services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server:${MINECRAFT_BEDROCK_DOCKER_TAG:-latest}
    container_name: ${MINECRAFT_BEDROCK_CONTAINER_NAME:-minecraft-bedrock} 
    restart: ${MINECRAFT_BEDROCK_RESTART:-unless-stopped}
    ports: 
      - 19132:19132/udp
    volumes:
      #- ./etc/minecraft-bedrock:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./etc/games/${MINECRAFT_BEDROCK_HOSTNAME:-minecraft-bedrock}:/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - EULA=TRUE
      - GAMEMODE=survival
      - DIFFICULTY=normal
    labels:
      - joyride.host.name=${MINECRAFT_BEDROCK_CONTAINER_NAME:-minecraft-bedrock}.${HOST_DOMAIN}
      - traefik.enable=false
      # - traefik.http.routers.minecraft-bedrock.entrypoints=websecure
      # - traefik.http.routers.minecraft-bedrock.rule=Host(`${MINECRAFT_BEDROCK_CONTAINER_NAME:-minecraft-bedrock}.${HOST_DOMAIN}`)
      # - traefik.http.services.minecraft-bedrock.loadbalancer.server.port=8096
      # - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${MINECRAFT_BEDROCK_FLAME_NAME:-minecraft-bedrock} 
      - flame.url=https://${MINECRAFT_BEDROCK_CONTAINER_NAME:-minecraft-bedrock}.${HOST_DOMAIN}
      - flame.icon=${MINECRAFT_BEDROCK_FLAME_ICON:-docker} # optional, default is "docker"