version: '3.8'

networks:
  default:
    name: ${MINECRAFT_DIREWOLF20_NETWORK:-games}

services:
  minecraft-direwolf20:
    image: itzg/minecraft-server:${MINECRAFT_DIREWOLF20_DOCKER_TAG:-java17}
    container_name: ${MINECRAFT_DIREWOLF20_CONTAINER_NAME:-minecraft-direwolf20}
    restart: ${MINECRAFT_DIREWOLF20_RESTART:-on-failure}
    environment:
      - EULA=true
      - TYPE=FTBA
      - FTB_MODPACK_ID=101
      - FTB_MODPACK_VERSON_ID=2297 #2312
      - VERSION=1.19.2
      - MAX_MEMORY=18G
      - MEMORY=12G
      - DISABLE_HEALTHCHECK=true
      - FTB_LEGACYJAVAFIXER=true
      - USE_AIKAR_FLAGS=true
      - MAX_TICK_TIME=-1
    ports:
      - ${MINECRAFT_DIREWOLF20_PORT:-25565}:25565
    volumes:
      - ./etc/games/${MINECRAFT_DIREWOLF20_HOSTNAME:-minecraft-direwolf20}:/data
    labels:
      - joyride.host.name=${MINECRAFT_DIREWOLF20_HOSTNAME:-minecraft-direwolf20}.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
