version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/apprise-api

services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:${APPRISE_DOCKER_TAG:-latest}
    container_name: ${APPRISE_CONTAINER_NAME:-apprise} 
    restart: ${APPRISE_RESTART:-unless-stopped}
    volumes:
      - ./etc/apprise:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${APPRISE_CONTAINER_NAME:-apprise}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.apprise.entrypoints=websecure
      - traefik.http.routers.apprise.rule=Host(`${APPRISE_CONTAINER_NAME:-apprise}.${HOST_DOMAIN}`)
      #- traefik.http.services.apprise.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.apprise.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${APPRISE_FLAME_NAME:-apprise} 
      - flame.url=https://${APPRISE_CONTAINER_NAME:-apprise}.${HOST_DOMAIN}
      - flame.icon=${APPRISE_FLAME_ICON:-docker} # optional, default is "docker"