version: '3'

networks:
  default:
    name: traefik

# https://goauthentik.io/docs/installation/docker-compose
# https://github.com/goauthentik/authentik
# https://goauthentik.io/docs/
# https://www.postgresql.org/

services:
  postgresql:
    image: postgres:${AUTHENTIK_POSTGRES_DOCKER_TAG:-latest}
    container_name: ${AUTHENTIK_POSTGRES_CONTAINER_NAME:-authentik_postgresql}
    restart: ${AUTHENTIK_POSTGRES_RESTART:-unless-stopped}
    user: "${PUID:-1000}:${PGID:-1000}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${AUTHENTIK_POSTGRES_DB} -U $${AUTHENTIK_POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./etc/authentik/postgresql:/var/lib/postgresql/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - POSTGRES_PASSWORD=${AUTHENTIK_POSTGRES_PASS:?authentik postgres database password required}
      - POSTGRES_USER=${AUTHENTIK_POSTGRES_USER:-authentik}
      - POSTGRES_DB=${AUTHENTIK_POSTGRES_DB:-authentik}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true   
       
  redis:
    image: redis:${AUTHENTIK_REDIS_DOCKER_TAG:-alpine}
    container_name: ${AUTHENTIK_REDIS_CONTAINER_NAME:-authentik_redis}
    restart: ${AUTHENTIK_REDIS_RESTART:-unless-stopped}
    volumes:
    - ./etc/authentik/redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true  

  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_DOCKER_TAG:-2023.6.1}
    container_name: ${AUTHENTIK_CONTAINER_NAME:-authentik_server}
    restart: ${AUTHENTIK_RESTART:-unless-stopped}
    command: server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRES_PASS}
      - AUTHENTIK_LOG_LEVEL=debug
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    user: authentik
    volumes:
      - ./etc/authentik/media:/media
      - ./etc/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./etc/authentik/geoip:/geoip
      # Uncomment above to enable the use of the geoipupdate container. This will allow more frequent updates but isn't required.
    labels:
      - joyride.host.name=${AUTHENTIK_AUTH_HOST:-authentik_server}.${AUTHENTIK_AUTH_DOMAIN}:-${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.rule=Host(`${AUTHENTIK_AUTH_HOST:-plex}.${AUTHENTIK_AUTH_DOMAIN}`) || HostRegexp(`{subdomain:[a-z]+}.${HOST_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.services.authentik.loadbalancer.server.port=9000
      - traefik.http.middlewares.authentik.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_DOCKER_TAG:-2023.6.1}
    container_name: ${AUTHENTIK_CONTAINER_NAME:-authentik_worker}
    restart: ${AUTHENTIK_RESTART:-unless-stopped}
    command: worker
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRES_PASS}
      - AUTHENTIK_LOG_LEVEL=debug
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}
      #- AUTHENTIK_GEOIP: /tmp/geoipdisabled
      # If you uncomment above it will disable GeoIP.
      #- AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # This is optional, and can be removed. If you remove this, the following will happen
      #- The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
      #- The docker socket can't be accessed anymore
    user: authentik
    volumes:
      - ./etc/authentik/media:/media
      - ./etc/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/authentik/custom-templates:/templates
      #- ./etc/authentik/geoip:/geoip
      # Uncomment above to enable the use of the geoipupdate container. This will allow more frequent updates but isn't required.
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true  

  #geoipupdate:
  #  image: maxmindinc/geoipupdate:latest
  #  volumes:
  #    - ./etc/authentik/geoip:/usr/share/GeoIP
  #  environment:
  #    - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
  #    - GEOIPUPDATE_FREQUENCY=8
  #    - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNT}
  #    - GEOIPUPDATE_LICENSE_KEY=${GEOIP_KEY}
  #  labels:
  #    - com.centurylinklabs.watchtower.enable=true
  #    - traefik.enable=false
  #    - autoheal=true
  #  env_file:
  #    - .env