version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/authelia/authelia

services:
  authelia:
    image: authelia/authelia:${AUTHELIA_DOCKER_TAG:-latest}
    container_name: ${AUTHELIA_CONTAINER_NAME:-authelia}
    restart: ${AUTHELIA_RESTART:-unless-stopped}
    expose:
      - 9091
    volumes:
      - ./etc/authelia:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - AUTHELIA_LOG_LEVEL=trace
      - AUTHELIA_DEFAULT_REDIRECTION_URL=https://${AUTHELIA_DOMAINHOST:-auth}.${HOST_DOMAIN}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_DOMAIN=${HOST_DOMAIN}
    labels:
      - joyride.host.name=${AUTHELIA_DOMAINHOST:-auth}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAINHOST:-auth}.${HOST_DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_DOMAINHOST:-auth}.${HOST_DOMAIN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true 