version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/bazarr

services:
  bazarr:
    image: linuxserver/bazarr:${BAZARR_DOCKER_TAG:-latest}
    container_name: ${BAZARR_CONTAINER_NAME:-bazarr}
    restart: ${BAZARR_RESTART:-unless-stopped}
    volumes:
      - ./etc/bazarr:/config
      - ${BAZARR_MOVIES_VOLUME:-./media/movies}:/movies
      - ${BAZARR_SHOWS_VOLUME:-./media/shows}:/tv
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${BAZARR_CONTAINER_NAME:-bazarr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.rule=Host(`${BAZARR_CONTAINER_NAME:-bazarr}.${HOST_DOMAIN}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
      
      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${BAZARR_FLAME_NAME:-bazarr} 
      - flame.url=https://${BAZARR_CONTAINER_NAME:-bazarr}.${HOST_DOMAIN}
      - flame.icon=${BAZARR_FLAME_ICON:-docker} # optional, default is "docker"