version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/google/cadvisor/
# https://github.com/google/cadvisor

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_DOCKER_TAG:-latest}
    container_name: ${CADVISOR_CONTAINER_NAME:-cadvisor}
    restart: ${CADVISOR_RESTART:-unless-stopped}
    command:
      - -allow_dynamic_housekeeping=false
      - -housekeeping_interval=30s
      - -storage_duration=1m0s
      - -docker_only=true
      #- -disable_metrics=accelerator,cpu_topology,disk,memory_numa,hugetlb,cpuset,advtcp,memory_numa
    #privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - org.label-schema.group=monitoring
      - joyride.host.name=${CADVISOR_CONTAINER_NAME:-cadvisor}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.cadvisor.rule=Host(`${CADVISOR_CONTAINER_NAME:-cadvisor}.${HOST_DOMAIN}`)
      - traefik.http.routers.cadvisor.entrypoints=websecure
      - traefik.http.routers.cadvisor.tls=true
      - traefik.http.routers.cadvisor.tls.certresolver=letsencrypt
      - traefik.http.services.cadvisor.loadbalancer.server.scheme=http
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true


      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${CADVISOR_FLAME_NAME:-Cadvisor} 
      - flame.url=https://${CADVISOR_CONTAINER_NAME:-cadvisor}.${HOST_DOMAIN}
      - flame.icon=${CADVISOR_FLAME_ICON:-plex} # optional, default is "docker"      