version: '3'

# https://github.com/oznu/docker-cloudflare-ddns

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:${CLOUDFLARE_DDNS_DOCKER_TAG:-latest} 
    container_name: ${CLOUDFLARE_DDNS_CONTAINER_NAME:-cloudflare-ddns}
    restart: ${CLOUDFLARE_DDNS_RESTART:-unless-stopped}
    environment:
      - EMAIL=${ONRAMP_CF_API_EMAIL}
      - API_KEY=${ONRAMP_CF_DNS_API_TOKEN}
      - ZONE=${HOST_DOMAIN}
      - SUBDOMAIN=${CLOUDFLARE_DDNS_HOSTNAME}
      - PROXIED=${CLOUDFLARE_DDNS_PROXIED:-false}
    labels:
      - traefik.enable=false