version: '3'

networks:
  default:
    name: traefik
    
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
# https://hub.docker.com/r/cloudflare/cloudflared
# https://github.com/cloudflare/cloudflared

services:
  cloudflared_chown:
    # https://github.com/cloudflare/cloudflared/issues/163
    image: privatebin/chown:1.34.1-musl-1.2.2-r3
    read_only: true
    command:
      - 65532:65532
      - /mnt
    volumes:
      - ./etc/cloudflare-tunnel:/mnt
      
  cloudflare-tunnel:
    image: cloudflare/cloudflared:${CLOUDFLARE_TUNNEL_DOCKER_TAG:-latest}
    container_name: ${CLOUDFLARE_TUNNEL_CONTAINER_NAME:-cloudflare-tunnel}
    restart: ${CLOUDFLARE_TUNNEL_RESTART:-unless-stopped}
    command: tunnel --url traefik:443 --hostname ${HOST_NAME}.${HOST_DOMAIN} run ${CLOUDFLARE_TUNNEL_NAME}
    depends_on:
      - cloudflared_chown
    volumes:
      - ./etc/cloudflare-tunnel:/home/nonroot/.cloudflared/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
