version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/crowdsecurity/crowdsec

services:
  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:${CROWDSEC_DOCKER_TAG:-latest}
    container_name: ${CROWDSEC_CONTAINER_NAME:-crowdsec} 
    restart: ${CROWDSEC_RESTART:-unless-stopped}
    volumes:
      - ./etc/crowdsec:/etc/crowdsec/
      - ./etc/crowdsec/db:/var/lib/crowdsec/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - COLLECTIONS="crowdsecurity/linux crowdsecurity/traefik"
    labels:
      #- joyride.host.name=${CROWDSEC_CONTAINER_NAME:-crowdsec}.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true