version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/gchq/CyberChef/

services:
  cyberchef:
    image: mpepping/cyberchef:${CYBERCHEF_DOCKER_TAG:-latest}
    container_name: ${CYBERCHEF_CONTAINER_NAME:-cyberchef}
    restart: ${CYBERCHEF_RESTART:-unless-stopped}
    volumes:
      - ./etc/cyberchef:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${CYBERCHEF_CONTAINER_NAME:-cyberchef}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.cyberchef.entrypoints=websecure
      - traefik.http.routers.cyberchef.rule=Host(`${CYBERCHEF_CONTAINER_NAME:-cyberchef}.${HOST_DOMAIN}`)
      #- traefik.http.services.cyberchef.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.cyberchef.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true