version: '3'

networks:
  default:
    name: traefik
    
# https://docs.gitlab.com/ee/install/docker.html

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_DOCKER_TAG:-latest}
    container_name: ${GITLAB_CONTAINER_NAME:-gitlab} 
    restart: ${GITLAB_RESTART:-unless-stopped}
    volumes:
      - ./etc/gitlab/config:/etc/config
      - ./etc/gitlab/data:/var/opt/gitlab
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - GITLAB_OMNIBUS_CONFIG=
          external_url 'https://${GITLAB_CONTAINER_NAME:-gitlab}.${HOST_DOMAIN}'; 
          #registry_external_url 'https://${GITLAB_CONTAINER_NAME:-gitlab}.${HOST_DOMAIN}'
          #registry['enable'] = true;
    ports:
      # - 4000:4000
      - "222:22"      
    labels:
      - joyride.host.name=${GITLAB_CONTAINER_NAME:-gitlab}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_CONTAINER_NAME:-gitlab}.${HOST_DOMAIN}`)
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.scheme=https
      - traefik.http.services.gitlab.loadbalancer.server.port=443
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${GITLAB_FLAME_NAME:-gitlab} 
      - flame.url=https://${GITLAB_CONTAINER_NAME:-gitlab}.${HOST_DOMAIN}
      - flame.icon=${GITLAB_FLAME_ICON:-docker} # optional, default is "docker"

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine
  #   container_name: gitlab-runner    
  #   restart: always
  #   depends_on:
  #     - gitlab
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./etc/gitlab/gitlab-runner:/etc/gitlab-runner
  #   # networks:
  #   #   - gitlab