version: "3"
networks:
  default:
    name: traefik
  loki:
    name: loki

# https://grafana.com/docs/grafana/next/setup-grafana/installation/docker/
# https://github.com/prometheus/prometheus

services:    
  grafana:
    image: grafana/grafana:${GRAFANA_DOCKER_TAG:-latest}
    container_name: ${GRAFANA_CONTAINER_NAME:-grafana}
    restart: ${GRAFANA_RESTART:-unless-stopped}
    user: ${PUID:-1000}
    networks:
      - default
      - loki
    environment:
      - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
    # ports:
    #   - 3000:3000
    volumes:
      - ./etc/grafana:/var/lib/grafana
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - joyride.host.name=${GRAFANA_CONTAINER_NAME:-grafana}.${HOST_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_CONTAINER_NAME:-grafana}.${HOST_DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.port=3000