version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/ajnart/homarr

services:
  homarr:
    image: ghcr.io/ajnart/homarr:${HOMARR_DOCKER_TAG:-dev}
    container_name: ${HOMARR_CONTAINER_NAME:-homarr} 
    restart: ${HOMARR_RESTART:-unless-stopped}
    volumes:
      - ./etc/homarr/configs:/app/data/configs
      - ./etc/homarr/icons:/app/public/icons
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      #- /var/run/docker.sock:/var/run/docker.sock #uncomment to enable docker control
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - BASE_URL=${HOMARR_CONTAINER_NAME:-homarr}.${HOST_DOMAIN}
    labels:
      - joyride.host.name=${HOMARR_CONTAINER_NAME:-homarr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.rule=Host(`${HOMARR_CONTAINER_NAME:-homarr}.${HOST_DOMAIN}`)
      - traefik.http.services.homarr.loadbalancer.server.port=7575
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${HOMARR_FLAME_NAME:-homarr} 
      - flame.url=https://${HOMARR_CONTAINER_NAME:-homarr}.${HOST_DOMAIN}
      - flame.icon=${HOMARR_FLAME_ICON:-docker} # optional, default is "docker"