version: '3'

# https://hub.docker.com/r/linuxserver/homeassistant

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:${HOMEASSISTANT_DOCKER_TAG:-latest}
    container_name: ${HOMEASSISTANT_CONTAINER_NAME:-homeassistant}
    restart: ${HOMEASSISTANT_RESTART:-unless-stopped}
    network_mode: host
    volumes:
      - ./etc/homeassistant:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000} 
      - TZ=${TZ}
    labels:
      - joyride.host.name=${HOMEASSISTANT_CONTAINER_NAME:-homeassistant}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.rule=Host(`${HOMEASSISTANT_CONTAINER_NAME:-homeassistant}.${HOST_DOMAIN}`)
      - traefik.http.services.homeassistant.loadbalancer.server.scheme=https
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true