version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  itflow:
    image: <==== container_image ====>:${ITFLOW_DOCKER_TAG:-latest}
    container_name: ${ITFLOW_CONTAINER_NAME:-itflow} 
    restart: ${ITFLOW_RESTART:-unless-stopped}
    volumes:
      - ./etc/itflow:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.itflow.entrypoints=websecure
      - traefik.http.routers.itflow.rule=Host(`${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}`)
      #- traefik.http.services.itflow.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.itflow.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${ITFLOW_FLAME_NAME:-itflow} 
      - flame.url=https://${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}
      - flame.icon=${ITFLOW_FLAME_ICON:-docker} # optional, default is "docker"