version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/jellyfin

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:${JELLYFIN_DOCKER_TAG:-latest}
    container_name: ${JELLYFIN_CONTAINER_NAME:-jellyfin}
    restart: ${JELLYFIN_RESTART:-unless-stopped}
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_CONTAINER_NAME:-jellyfin}.${HOST_DOMAIN}
    volumes:
      - ${JELLYFIN_CONFIG_VOLUME:-./etc/jellyfin}:/config
      - ${JELLYFIN_MEDIA_VOLUME:-./media}:${JELLYFIN_MEDIA_PATH:-/data}
    ports:
      # - 8096:8096 # http web gui
      # - 8920:8920 # https web gui
      - 7359:7359/udp # Jellyfin client discovery
      - 1900:1900/udp # DNLA discovery
    labels:
      - joyride.host.name=${JELLYFIN_CONTAINER_NAME:-jellyfin}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_CONTAINER_NAME:-jellyfin}.${HOST_DOMAIN}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

