version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/tobybatch/kimai2
# https://github.com/kevinpapst/kimai2

services:
  kimai:
    image: kimai/kimai2:${KIMAI_DOCKER_TAG:-apache}
    container_name: ${KIMAI_CONTAINER_NAME:-kimai} 
    restart: ${KIMAI_RESTART:-unless-stopped}
    volumes:
      #- ./etc/kimai:/opt/kimai/public
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - DATABASE_URL=mysql://kimai:kimaipassword@mariadb/kimai
      - TRUSTED_HOSTS=localhost,127.0.0.1,${KIMAI_CONTAINER_NAME:-kimai}.${HOST_DOMAIN}
    labels:
      - joyride.host.name=${KIMAI_CONTAINER_NAME:-kimai}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.kimai.entrypoints=websecure
      - traefik.http.routers.kimai.rule=Host(`${KIMAI_CONTAINER_NAME:-kimai}.${HOST_DOMAIN}`)
      - traefik.http.services.kimai.loadbalancer.server.port=8001
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
    
      

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${KIMAI_FLAME_NAME:-kimai} 
      - flame.url=https://${KIMAI_CONTAINER_NAME:-kimai}.${HOST_DOMAIN}
      - flame.icon=${KIMAI_FLAME_ICON:-docker} # optional, default is "docker"