version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/lidarr

services:
  lidarr:
    image: linuxserver/lidarr:${LIDARR_DOCKER_TAG:-latest}
    container_name: ${LIDARR_CONTAINER_NAME:-lidarr}
    restart: ${LIDARR_RESTART:-unless-stopped}
    volumes:
      - ./etc/lidarr:/config
      - ${LIDARR_MUSIC_VOLUME:-./media/music}:/music
      - ${LIDARR_DOWNLOADS_VOLUME:-./media/downloads}:/downloads
      # - /dev/rtc:/dev/rtc:ro
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${LIDARR_CONTAINER_NAME:-lidarr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.rule=Host(`${LIDARR_CONTAINER_NAME:-lidarr}.${HOST_DOMAIN}`)
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
