version: '3'

# https://hub.docker.com/_/eclipse-mosquitto

services:
  mosquitto-mqtt:
    image: eclipse-mosquitto:${MOSQUITTO_DOCKER_TAG:-latest}
    container_name: ${MOSQUITTO_CONTAINER_NAME:-mosquitto}
    restart: ${MOSQUITTO_RESTART:-unless-stopped}

    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - ./etc/mosquitto/config:/mosquitto/config
      - ./etc/mosquitto/data:/mosquitto/data
      - ./etc/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    labels:
      - autoheal=true
      - traefik.enable=false
      - joyride.host.name=${MOSQUITTO_CONTAINER_NAME:-mosquitto}.${HOST_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true