version: '3'

networks:
  default:
    name: traefik
    
# https://docs.linuxserver.io/images/docker-netbootxyz

services:
  netbootxyz:
    image: linuxserver/netbootxyz:${NETBOOTXYZ_DOCKER_TAG:-latest}
    container_name: ${NETBOOTXYZ_CONTAINER_NAME:-netbootxyz} 
    restart: ${NETBOOTXYZ_RESTART:-unless-stopped}
    volumes:
      - ./etc/netbootxyz:/config
      - ./media/netbootxyz:/assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 69:69/udp
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      # - MENU_VERSION=1.9.9
      # - PORT_RANGE=30000:30010
      # - SUBFOLDER=/
    labels:
      - joyride.host.name=${NETBOOTXYZ_CONTAINER_NAME:-netbootxyz}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.netbootxyz.entrypoints=websecure
      - traefik.http.routers.netbootxyz.rule=Host(`${NETBOOTXYZ_CONTAINER_NAME:-netbootxyz}.${HOST_DOMAIN}`)
      - traefik.http.services.netbootxyz.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${NETBOOTXYZ_FLAME_NAME:-netbootxyz} 
      - flame.url=https://${NETBOOTXYZ_CONTAINER_NAME:-netbootxyz}.${HOST_DOMAIN}
      - flame.icon=${NETBOOTXYZ_FLAME_ICON:-docker} # optional, default is "docker"