version: '3'

networks:
  default:
    name: traefik

volumes:
  redis:
    
# https://github.com/buzz/newsdash

services:
  newsdash:
    image: newsdash/newsdash:${NEWSDASH_DOCKER_TAG:-latest}
    container_name: ${NEWSDASH_CONTAINER_NAME:-newsdash}
    restart: ${NEWSDASH_RESTART:-unless-stopped}
    volumes:
      - ./etc/newsdash:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_URL=redis://newsdash-redis:6380
    labels:
      - joyride.host.name=${NEWSDASH_CONTAINER_NAME:-newsdash}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.newsdash.entrypoints=websecure
      - traefik.http.routers.newsdash.rule=Host(`newsdash.${HOST_DOMAIN}`)
      - traefik.http.services.newsdash.loadbalancer.server.port=3001
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  redis:
    image: bitnami/redis
    container_name: newsdash-redis
    restart: ${NEWSDASH_RESTART:-unless-stopped}
    mem_limit: 1g
    command: /opt/bitnami/scripts/redis/run.sh --loglevel ${NEWSDASH_REDIS_LOG_LEVEL:-notice}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitnami