version: '3'

networks:
  default:
    name: traefik
    
#  https://hub.docker.com/r/linuxserver/nzbget

services:
  nzbget:
    image: linuxserver/nzbget:${NZBGET_DOCKER_TAG:-latest}
    container_name: ${NZBGET_CONTAINER_NAME:-nzbget} 
    restart: ${NZBGET_RESTART:-unless-stopped}
    volumes:
      - ./etc/nzbget:/config
      - ${NZBGET_DOWNLOADS_DIR:-./media/downloads}:/downloads
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:6789 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=${NZBGET_CONTAINER_NAME:-nzbget}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.nzbget.entrypoints=websecure
      - traefik.http.routers.nzbget.rule=Host(`${NZBGET_CONTAINER_NAME:-nzbget}.${HOST_DOMAIN}`)
      - traefik.http.services.nzbget.loadbalancer.server.port=6789
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${NZBGET_FLAME_NAME:-nzbget} 
      - flame.url=https://${NZBGET_CONTAINER_NAME:-nzbget}.${HOST_DOMAIN}
      - flame.icon=${NZBGET_FLAME_ICON:-docker} # optional, default is "docker"