version: '3'

networks:
  default:
    name: traefik

# https://github.com/OliveTin/OliveTin

services:
  olivetin:
    image: jamesread/olivetin:${OLIVETIN_DOCKER_TAG:-latest}
    container_name: ${OLIVETIN_CONTAINER_NAME:-olivetin}
    restart: ${OLIVETIN_RESTART:-unless-stopped}
    volumes:
      - ./etc/olivetin:/config # replace host path or volume as needed
    # ports:
    #   - 1337:1337
    labels:
      - joyride.host.name=${OLIVETIN_CONTAINER_NAME:-olivetin}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.olivetin.entrypoints=websecure
      - traefik.http.routers.olivetin.rule=Host(`${OLIVETIN_CONTAINER_NAME:-olivetin}.${HOST_DOMAIN}`)
      - traefik.http.services.olivetin.loadbalancer.server.port=1337
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true