version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/mbentley/omada-controller

# Article on issues with device adoption
# https://www.tp-link.com/us/support/faq/3192/

services:
  omada:
    image: mbentley/omada-controller:${OMADA_DOCKER_TAG:-latest}
    container_name: ${OMADA_CONTAINER_NAME:-omada} 
    restart: ${OMADA_RESTART:-unless-stopped}
    volumes:
      - ${OMADA_CONFIG_DIR:-./etc/omada}/data:/opt/tplink/EAPController/data
      - ${OMADA_WORK_DIR:-./etc/omada}/work:/opt/tplink/EAPController/work
      - ${OMADA_LOGS_DIR:-./etc/omada}/logs:/opt/tplink/EAPController/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      # Keep in mind that these only apply on first start
      - MANAGE_HTTP_PORT=${OMADA_MANAGE_HTTP_PORT:-8088}
      - MANAGE_HTTPS_PORT=${OMADA_MANAGE_HTTPS_PORT:-443}
      - PORTAL_HTTP_PORT=${OMADA_PORTAL_HTTP_PORT:-8088}
      - PORTAL_HTTPS_PORT=${OMADA_PORTAL_HTTPS_PORT:-8043}
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
    ports:
      # Below ports required for portal access
      - '8088:8088'
      - '8043:8043'
      # - '27001:27001/udp'
      # - '27002:27002'
      # - '27017:27017'
      # Below ports required for device discovery
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'

    labels:
      - joyride.host.name=${OMADA_CONTAINER_NAME:-omada}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.omada.entrypoints=websecure
      - traefik.http.routers.omada.rule=Host(`${OMADA_CONTAINER_NAME:-omada}.${HOST_DOMAIN}`)
      - traefik.http.services.omada.loadbalancer.server.scheme=https
      - traefik.http.services.omada.loadbalancer.server.port=443
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${OMADA_FLAME_NAME:-omada} 
      - flame.url=https://${OMADA_CONTAINER_NAME:-omada}.${HOST_DOMAIN}
      - flame.icon=${OMADA_FLAME_ICON:-server-network} # optional, default is "docker"