version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/overseerr

services:
  overseerr:
    image: linuxserver/overseerr:${OVERSEERR_DOCKER_TAG:-latest}
    container_name: ${OVERSEERR_CONTAINER_NAME:-overseerr} 
    restart: ${OVERSEER_RESTART:-unless-stopped}
    volumes:
      - ./etc/overseerr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${OVERSEERR_CONTAINER_NAME:-overseerr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.rule=Host(`${OVERSEERR_CONTAINER_NAME:-overseerr}.${HOST_DOMAIN}`)
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${OVERSEERR_FLAME_NAME:-overseerr} 
      - flame.url=https://${OVERSEERR_CONTAINER_NAME:-overseerr}.${HOST_DOMAIN}
      - flame.icon=${OVERSEERR_FLAME_ICON:-docker} # optional, default is "docker"