version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/paperless-ngx
# https://github.com/paperless-ngx/paperless-ngx
# https://docs.paperless-ngx.com/

services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperlessngx-broker
    restart: unless-stopped
    volumes:
      - ./etc/paperless-ngx/redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    container_name: paperlessngx-db
    restart: unless-stopped
    volumes:
      - ./etc/paperless-ngx/dbdata:/var/lib/mysql
    environment:
      - MARIADB_HOST=${PAPERLESSNGX_DB_HOST:-paperless}
      - MARIADB_DATABASE=${PAPERLESSNGX_DB_NAME:-paperless}
      - MARIADB_USER=${PAPERLESSNGX_DB_USER:-paperless}
      - MARIADB_PASSWORD=${PAPERLESSNGX_DB_PASS:-paperless}
      - MARIADB_ROOT_PASSWORD=${PAPERLESSNGX_DB_ROOTPASS:-paperless}
    ports:
      - "3306:3306"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.6
    container_name: paperlessngx-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperlessngx-tika
    restart: unless-stopped

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESSNGX_DOCKER_TAG:-latest}
    container_name: ${PAPERLESSNGX_CONTAINER_NAME:-paperless-ngx} 
    restart: ${PAPERLESSNGX_RESTART:-unless-stopped}
    depends_on:
      - broker
      - db  
      - gotenberg
      - tika
    volumes:
      - ./etc/paperless-ngx/data:/usr/src/paperless/data
      - ./etc/paperless-ngx/media:/usr/src/paperless/media
      - ./etc/paperless-ngx/export:/usr/src/paperless/export
      - ./etc/paperless-ngx/consume:/usr/src/paperless/consume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PAPERLESS_URL=https://${PAPERLESSNGX_CONTAINER_NAME:-paperless-ngx}.${HOST_DOMAIN} #Required for proper authentication behind traefik
      - PAPERLESS_REDIS=redis://paperlessngx-broker:6379
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperlessngx-gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://paperlessngx-tika:9998
      - PAPERLESS_DBENGINE=${PAPERLESSNGX_DB_ENGINE:-mariadb}
      - PAPERLESS_DBPORT=${PAPERLESSNGX_DB_PORT:-3306}
      - PAPERLESS_DBHOST=${PAPERLESSNGX_DB_HOST:-db}
      - PAPERLESS_DBNAME=${PAPERLESSNGX_DB_NAME:-paperless}
      - PAPERLESS_DBUSER=${PAPERLESSNGX_DB_USER:-paperless}
      - PAPERLESS_DBPASS=${PAPERLESSNGX_DB_PASS:-paperless}
      - PAPERLESS_ADMIN_USER=${PAPERLESSNGX_ADMINUSER:-admin}
      - PAPERLESS_ADMIN_MAIL=${PAPERLESSNGX_ADMINMAIL:-admin@yourmail.com}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESSNGX_ADMINPASSWORD:-admin}
    labels:
      - joyride.host.name=${PAPERLESSNGX_CONTAINER_NAME:-paperless-ngx}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.paperless-ngx.entrypoints=websecure
      - traefik.http.routers.paperless-ngx.rule=Host(`${PAPERLESSNGX_CONTAINER_NAME:-paperless-ngx}.${HOST_DOMAIN}`)
      - traefik.http.services.paperless-ngx.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${PAPERLESSNGX_FLAME_NAME:-paperless-ngx} 
      - flame.url=https://${PAPERLESSNGX_CONTAINER_NAME:-paperless-ngx}.${HOST_DOMAIN}
      - flame.icon=${PAPERLESSNGX_FLAME_ICON:-docker} # optional, default is "docker"