version: '3'

networks:
  default:
    name: traefik
    
# https://www.pgadmin.org/
# https://hub.docker.com/r/dpage/pgadmin4/

services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_DOCKER_TAG:-latest}
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    restart: ${PGADMIN_RESTART:-unless-stopped}
    volumes:
      - ./etc/pgadmin:/var/lib/pgadmin4
      - ./etc/pgadmin/servers.json:/pgadmin4/servers.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # - PUID=${PUID:-1000}
      # - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-$ONRAMP_CF_API_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-pgadmin}
      - PGADMIN_DEFAULT_SERVER=${PGADMIN_DEFAULT_SERVER:-postgresql}
    labels:
      - joyride.host.name=${PGADMIN_CONTAINER_NAME:-pgadmin}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_CONTAINER_NAME:-pgadmin}.${HOST_DOMAIN}`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true