version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/mafen/playit-docker
# https://github.com/playit-cloud/playit-agent

services:
  playit-docker:
    image: ghcr.io/mafen/playit-docker:${PLAYITDOCKER_DOCKER_TAG:-latest}
    container_name: ${PLAYITDOCKER_CONTAINER_NAME:-playit-docker} 
    restart: ${PLAYIT_DOCKER_RESTART:-unless-stopped}
    volumes:
      #- ./etc/playit-docker:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true