version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/plexinc/pms-docker
# https://www.plex.tv/claim

services:
  plex:
    image: plexinc/pms-docker:${PLEX_DOCKER_TAG:-latest}
    container_name: ${PLEX_CONTAINER_NAME:-plex}
    restart: ${PLEX_RESTART:-unless-stopped}
    volumes:
      - ${PLEX_CONFIG_VOLUME:-./etc/plex}:/config
      - ${PLEX_MEDIA_VOLUME:-./media}:${PLEX_MEDIA_PATH:-/data}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- 32400:32400/tcp
      #- 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP:-https://${PLEX_CONTAINER_NAME:-plex}.${HOST_DOMAIN}}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${PGID:-1000}
      - VERSION=docker
    # env_file:
    #   - .env
    labels:
      - joyride.host.name=${PLEX_CONTAINER_NAME:-plex}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.rule=Host(`${PLEX_CONTAINER_NAME:-plex}.${HOST_DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${PLEX_FLAME_NAME:-Plex} 
      - flame.url=https://${PLEX_CONTAINER_NAME:-plex}.${HOST_DOMAIN}
      - flame.icon=${PLEX_FLAME_ICON:-plex} # optional, default is "docker"