version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/prestashop/prestashop/
# https://www.prestashop.com/en

services:
  prestashop:
    image: prestashop/prestashop:${PRESTASHOP_DOCKER_TAG:-latest}
    container_name: ${PRESTASHOP_CONTAINER_NAME:-prestashop} 
    restart: ${PRESTASHOP_RESTART:-unless-stopped}
    volumes:
      - ./etc/prestashop:/var/www/html/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PS_DOMAIN=${PRESTASHOP_CONTAINER_NAME:-prestashop}.${HOST_DOMAIN}
    labels:
      - joyride.host.name=${PRESTASHOP_CONTAINER_NAME:-prestashop}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.prestashop.entrypoints=websecure
      - traefik.http.routers.prestashop.rule=Host(`${PRESTASHOP_CONTAINER_NAME:-prestashop}.${HOST_DOMAIN}`)
      - traefik.http.services.prestashop.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${PRESTASHOP_FLAME_NAME:-prestashop} 
      - flame.url=https://${PRESTASHOP_CONTAINER_NAME:-prestashop}.${HOST_DOMAIN}
      - flame.icon=${PRESTASHOP_FLAME_ICON:-docker} # optional, default is "docker"