version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/pwndrop

services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:${PWNDROP_DOCKER_TAG:-latest}
    container_name: ${PWNDROP_CONTAINER_NAME:-pwndrop}
    restart: ${PWNDROP_RESTART:-unless-stopped}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SECRET_PATH=${PWNDROP_SECRET_PATH:-/pwndrop}
    volumes:
      - ./etc/pwndrop:/config
    labels:
      - joyride.host.name=${PWNDROP_CONTAINER_NAME:-pwndrop}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.pwndrop.rule=Host(`${PWNDROP_CONTAINER_NAME:-pwndrop}.${HOST_DOMAIN}`)
      - traefik.http.routers.pwndrop.entrypoints=websecure
      - traefik.http.services.pwndrop.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true