version: '3'

networks:
  default:
    name: traefik

# https://github.com/koush/scrypted    
# https://docs.technotim.live/posts/scrypted-home-hub/

services:
  scrypted:
    image: koush/scrypted:${SCRYPTED_DOCKER_TAG:-latest}
    container_name: ${SCRYPTED_CONTAINER_NAME:-scrypted} 
    restart: ${SCRYPTED_RESTART:-unless-stopped}
    network_mode: host
    volumes:
      - ./etc/scrypted:/server/volume
      - ./media/videos/scrypted:/media/external
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=${SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION}
      - SCRYPTED_WEBHOOK_UPDATE=${SCRYPTED_WEBHOOK_UPDATE:-http://localhost:10444/v1/update}
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "10"
    labels:
      - joyride.host.name=${SCRYPTED_CONTAINER_NAME:-scrypted}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.scrypted.entrypoints=websecure
      - traefik.http.routers.scrypted.rule=Host(`${SCRYPTED_CONTAINER_NAME:-scrypted}.${HOST_DOMAIN}`)
      #- traefik.http.services.scrypted.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.scrypted.loadbalancer.server.port=10444
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${SCRYPTED_FLAME_NAME:-scrypted} 
      - flame.url=https://${SCRYPTED_CONTAINER_NAME:-scrypted}.${HOST_DOMAIN}
      - flame.icon=${SCRYPTED_FLAME_ICON:-docker} # optional, default is "docker"