version: '3'

networks:
  default:
    name: traefik
    
# https://docs.ansible-semaphore.com/

services:
  mysql:
    image: mysql:8.0
    container_name: semephore-mysql
    restart: unless-stopped
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./etc/semaphore/data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD='yes'
      MYSQL_DATABASE=${SEMAPHORE_DB_HOST:-mysql}
      MYSQL_USER=${SEMAPHORE_DB_USER:-semaphore}
      MYSQL_PASSWORD=${SEMAPHORE_DB_PASS:-semaphore}

  semaphore:
    image: semaphoreui/semaphore:${SEMAPHORE_DOCKER_TAG:-latest}
    container_name: ${SEMAPHORE_CONTAINER_NAME:-semaphore} 
    restart: ${SEMAPHORE_RESTART:-unless-stopped}
    depends_on:
      - mysql #change to postgres for postgres
    volumes:
      #- ./etc/semaphore:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SEMAPHORE_DB_USER=${SEMAPHORE_DB_USER:-semaphore}
      - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS:-semaphore}
      - SEMAPHORE_DB_HOST=${SEMAPHORE_DB_HOST:-mysql}
      - SEMAPHORE_DB_PORT=${SEMAPHORE_DB_PORT:-3306}
      - SEMAPHORE_DB_DIALECT=${SEMAPHORE_DB_DIALECT:-mysql}
      - SEMAPHORE_DB=${SEMAPHORE_DB:-semaphore}
      - SEMAPHORE_PLAYBOOK_PATH=${SEMAPHORE_PLAYBOOK_PATH:-/tmp/semaphore/}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD:-changeme}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME:-admin}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN:-admin}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION:-gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=}
      - SEMAPHORE_LDAP_ACTIVATED=${SEMAPHORE_LDAP_ACTIVATED:-'no'}
      - SEMAPHORE_LDAP_HOST=${SEMAPHORE_LDAP_HOST:-dc01.local.example.com}
      - SEMAPHORE_LDAP_PORT=${SEMAPHORE_LDAP_PORT:-'636'}
      - SEMAPHORE_LDAP_NEEDTLS=${SEMAPHORE_LDAP_NEEDTLS:-'yes'}
      - SEMAPHORE_LDAP_DN_BIND=${SEMAPHORE_LDAP_DN_BIND:-'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'}
      - SEMAPHORE_LDAP_PASSWORD=${SEMAPHORE_LDAP_PASSWORD:-'ldap_bind_account_password'}
      - SEMAPHORE_LDAP_DN_SEARCH=${SEMAPHORE_LDAP_SEARCH:-'dc=local,dc=example,dc=com'}
      - SEMAPHORE_LDAP_SEARCH_FILTER=${SEMAPHORE_LDAP_SEARCH_FILTER:-"(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"}

    labels:
      - joyride.host.name=${SEMAPHORE_CONTAINER_NAME:-semaphore}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.semaphore.entrypoints=websecure
      - traefik.http.routers.semaphore.rule=Host(`${SEMAPHORE_CONTAINER_NAME:-semaphore}.${HOST_DOMAIN}`)
      - traefik.http.services.semaphore.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${SEMAPHORE_FLAME_NAME:-semaphore} 
      - flame.url=https://${SEMAPHORE_CONTAINER_NAME:-semaphore}.${HOST_DOMAIN}
      - flame.icon=${SEMAPHORE_FLAME_ICON:-docker} # optional, default is "docker"