version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/haugene/transmission-openvpn
# https://haugene.github.io/docker-transmission-openvpn/

services:
  transmission-vpn:
    image: haugene/transmission-openvpn:${TRANSMISSION_VPN_DOCKER_TAG:-latest}
    container_name: ${TRANSMISSION_VPN_CONTAINER_NAME:-transmission-vpn} 
    restart: ${TRANSMISSION_VPN_RESTART:-unless-stopped}
    volumes:
      - ./etc/transmission-vpn:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9091:9091
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=${TRANSMISSION_VPN_WEBUI:-combustion}
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/downloads/torrents      
      - OPENVPN_PROVIDER=${TRANSMISSION_VPN_PROVIDER:-PIA}
      - OPENVPN_CONFIG=${TRANSMISSION_VPN_CONFIG:-france}
      - OPENVPN_USERNAME=${TRANSMISSION_VPN_USERNAME:-user}
      - OPENVPN_PASSWORD=${TRANSMISSION_VPN_PASSWORD:-pass}
      - LOCAL_NETWORK=${TRANSMISSION_VPN_LOCAL_NETWORK:-192.168.0.0/16}
      - OPENVPN_IPV6=off
      - DISABLE_PORT_UPDATER=true
      - OVERRIDE_DNS_1=1.1.1.1
      - OVERRIDE_DNS_2=1.0.0.1      

    logging:
      driver: json-file
      options:
        max-size: 10m      
    labels:
      - joyride.host.name=${TRANSMISSION_VPN_CONTAINER_NAME:-transmission-vpn}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.transmission-vpn.entrypoints=websecure
      - traefik.http.routers.transmission-vpn.rule=Host(`${TRANSMISSION_VPN_CONTAINER_NAME:-transmission-vpn}.${HOST_DOMAIN}`)
      - traefik.http.services.transmission-vpn.loadbalancer.server.port=9091
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${TRANSMISSION_VPN_FLAME_NAME:-transmission-vpn} 
      - flame.url=https://${TRANSMISSION_VPN_CONTAINER_NAME:-transmission-vpn}.${HOST_DOMAIN}
      - flame.icon=${TRANSMISSION_VPN_FLAME_ICON:-docker} # optional, default is "docker"

