version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/zadam/trilium
# https://github.com/BaptisteBdn/docker-selfhosted-apps/tree/main/trilium

services:
  trilium:
    image: zadam/trilium:${TRILIUM_DOCKER_TAG:-latest}
    container_name: ${TRILIUM_CONTAINER_NAME:-trilium} 
    restart: ${TRILIUM_RESTART:-unless-stopped}
    volumes:
      - ./etc/trilium:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TRILIUM_DATA_DIR=/data
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${TRILIUM_CONTAINER_NAME:-trilium}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.trilium.entrypoints=websecure
      - traefik.http.routers.trilium.rule=Host(`${TRILIUM_CONTAINER_NAME:-trilium}.${HOST_DOMAIN}`)
      - traefik.http.services.trilium.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true