version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/ixsystems/truecommand

services:
  truecommand:
    image: ixsystems/truecommand:${TRUECOMMAND_DOCKER_TAG:-latest}
    container_name: ${TRUECOMMAND_CONTAINER_NAME:-truecommand} 
    restart: ${TRUECOMMAND_RESTART:-unless-stopped}
    volumes:
      - ./etc/truecommand:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${TRUECOMMAND_CONTAINER_NAME:-truecommand}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.truecommand.entrypoints=websecure
      - traefik.http.routers.truecommand.rule=Host(`${TRUECOMMAND_CONTAINER_NAME:-truecommand}.${HOST_DOMAIN}`)
      - traefik.http.services.truecommand.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${TRUECOMMAND_FLAME_NAME:-truecommand} 
      - flame.url=https://${TRUECOMMAND_CONTAINER_NAME:-truecommand}.${HOST_DOMAIN}
      - flame.icon=${TRUECOMMAND_FLAME_ICON:-docker} # optional, default is "docker"

