version: "3"

services:
  ubuntu:
    image: ubuntu:${UBUNTU_DOCKER_TAG:-latest}
    container_name: ${UBUNTU_CONTAINER_NAME:-ubuntu}
    restart: ${UBUNTU_RESTART:-on-failure}
    volumes:
      - ${UBUNTU_TEST_VOLUME:-.}:/mnt