version: '3'

networks:
  default:
    name: traefik

# https://github.com/dani-garcia/vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_DOCKER_TAG:-latest}
    container_name: ${VAULTWARDEN_CONTAINER_NAME:-vaultwarden}
    restart: ${VAULTWARDEN_RESTART:-unless-stopped}
    volumes:
      - ./etc/vaultwarden:/data
      - /dev/rtc:/dev/rtc:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_SECRET}
    labels:
      - joyride.host.name=${VAULTWARDEN_CONTAINER_NAME:-vaultwarden}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_CONTAINER_NAME:-vaultwarden}.${HOST_DOMAIN}`)
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true