version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/SECUREFOREST/WebMap

services:
  webmap:
    image: secureforest/webmap:${WEBMAP_DOCKER_TAG:-latest}
    container_name: ${WEBMAP_CONTAINER_NAME:-webmap}
    restart: ${WEBMAP_RESTART:-unless-stopped}
    volumes:
      - ${WEBMAP_CONFIG_PATH:-./etc/webmap}:/opt/xml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${WEBMAP_CONTAINER_NAME:-webmap}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.webmap.entrypoints=websecure
      - traefik.http.routers.webmap.rule=Host(`${WEBMAP_CONTAINER_NAME:-webmap}.${HOST_DOMAIN}`)
      - traefik.http.services.webmap.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true