version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/linuxserver/docker-webtop

services:
  webtop:
    image: lscr.io/linuxserver/webtop:${WEBTOP_DOCKER_TAG:-latest}
    container_name: ${WEBTOP_CONTAINER_NAME:-webtop} 
    restart: ${WEBTOP_RESTART:-unless-stopped}
    volumes:
      - ./etc/webtop:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${WEBTOP_CONTAINER_NAME:-webtop}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.webtop.entrypoints=websecure
      - traefik.http.routers.webtop.rule=Host(`${WEBTOP_CONTAINER_NAME:-webtop}.${HOST_DOMAIN}`)
      - traefik.http.services.webtop.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${WEBTOP_FLAME_NAME:-webtop} 
      - flame.url=https://${WEBTOP_CONTAINER_NAME:-webtop}.${HOST_DOMAIN}
      - flame.icon=${WEBTOP_FLAME_ICON:-docker} # optional, default is "docker"