version: '3'

networks:
  default:
    name: traefik
    
# https://wordpress.com/
# https://hub.docker.com/_/wordpress


services:
  wordpress:
    image: wordpress:${WORDPRESS_DOCKER_TAG:-latest}
    container_name: ${WORDPRESS_CONTAINER_NAME:-wordpress} 
    restart: ${WORDPRESS_RESTART:-unless-stopped}
    volumes:
      - ./etc/wordpress:/var/www/html/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - WORDPRESS_DB_HOST=${WORDPRESS_DATABASE_HOST:-mariadb}
      - WORDPRESS_DB_USER=${WORDPRESS_DATABASE_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DATABASE_NAME:-wordpress}
    ports:
      - 8080:80
    labels:
      - joyride.host.name=${WORDPRESS_CONTAINER_NAME:-wordpress}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_CONTAINER_NAME:-wordpress}.${HOST_DOMAIN}`)
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${WORDPRESS_FLAME_NAME:-wordpress} 
      - flame.url=https://${WORDPRESS_CONTAINER_NAME:-wordpress}.${HOST_DOMAIN}
      - flame.icon=${WORDPRESS_FLAME_ICON:-docker} # optional, default is "docker"